services:
  launch3d:
    image: launch3d:local
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SLURM_GPU_OPTIONS=${NEXT_PUBLIC_SLURM_GPU_OPTIONS}
        - NEXT_PUBLIC_SLURM_MAX_CPUS=${NEXT_PUBLIC_SLURM_MAX_CPUS}
        - NEXT_PUBLIC_STORAGE_PATH=${NEXT_PUBLIC_STORAGE_PATH}
    volumes:
      - /cert.cer:${LDAP_CERTIFICATE_PATH}:ro
    env_file:
      - .env