services:
  launch3d:
    image: launch3d:local
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SLURM_GPU_OPTIONS=${NEXT_PUBLIC_SLURM_GPU_OPTIONS}
        - NEXT_PUBLIC_SLURM_MAX_CPUS=${NEXT_PUBLIC_SLURM_MAX_CPUS}
    volumes:
      - /cert.cer:${LDAP_CERTIFICATE_PATH}:ro
    environment:  
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - LDAP_CERTIFICATE_PATH=${LDAP_CERTIFICATE_PATH}
      - LDAP_URL=${LDAP_URL}
      - SSH_HOST=${SSH_HOST}
      - SSH_PASSPHRASE=${SSH_PASSPHRASE}
      - SSH_KEYS_PATH=${SSH_KEYS_PATH}
      - ANNOTAT3D_IMAGE_PATH=${ANNOTAT3D_IMAGE_PATH}
      - ANNOTAT3D_PORT_RANGE0=${ANNOTAT3D_PORT_RANGE0}
      - ANNOTAT3D_PORT_RANGE1=${ANNOTAT3D_PORT_RANGE1}